title: My blog
author: Gerardo Martinez
email: gmart_nez@yahoo.com.mx
description: > # this means to ignore newlines until "baseurl:"
  Gerardo Martinez's blog

# social links
twitter_username: rombo84fx
github_username:  rombo84fx

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
